import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./pages/navbar/page";

const poppins = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-slate-100`}>
        <div className="px-20">
          <Navbar />
        </div>

        <div className="px-20">{children}</div>

        {/* <footer>This is footer</footer> */}
      </body>
    </html>
  );
}
