import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./pages/navbar/page";
import FooterSection from "./footer/page";
import Head from "next/head";

const poppins = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "QT Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta
          http-equiv="Content-Security-Policy"
          content="upgrade-insecure-requests"
        />
      </Head>
      <body className={`${poppins.className} bg-slate-100`}>
        <Navbar />
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
